apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meta-pod
  template:
    metadata:
      labels:
        app: meta-pod
    spec:
      containers:
        - name: meta-cont
          image: sunitparekh/metadata:v1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3