apiVersion: v1
kind: Service
metadata:
  name: svc-test
spec:
  type: NodePort
#  type: ClusterIP
  selector:
    app: meta-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001