apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: meta-pod
  template:
    metadata:
      labels:
        app: meta-pod
    spec:
      containers:
        - name: meta-cont
          image: sunitparekh/metadata:v1.0
          ports:
            - containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 20
#            periodSeconds: 3
          env:
            - name: VERSION
              value: "5.0"
